blank_issues_enabled: false
contact_links:
  - name: Discord Chat
    url: https://discord.com/invite/YREMzGQ3gd
    about: Please ask questions here, or just come in to socialize with other fans of randomizers!
