name: Environmental Station Alpha
comment: null
sub-series: null
randomizers:
-   games:
    - Environmental Station Alpha
    identifier: Mokesmoe's
    url: https://www.speedrun.com/esalpha/resources
    comment: 'Located under Tools'
